name: Update gfwlist

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main

jobs:
  update-gfwlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download gfwlist.txt
        run: curl -O https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

      - name: Decode base64
        run: base64 -d gfwlist.txt > decoded_gfwlist.txt

      - name: Process decoded file
        run: |
          grep -v '^!' decoded_gfwlist.txt | grep -v '^@' | grep -v '^\[' > processed_gfwlist.txt

      - name: Replace '||' with empty value
        run: sed -i 's/||//g' processed_gfwlist.txt

      - name: Delete lines starting with '|'
        run: sed -i '/^|/d' processed_gfwlist.txt

      - name: Create data directory
        run: mkdir -p data

      - name: Move processed file
        run: mv processed_gfwlist.txt data/

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add data/processed_gfwlist.txt
          git commit -m "Update processed gfwlist" || echo "No changes to commit"
          git push
